### ISSUE TITLE
User Signed Out

### ISSUE THREAD

**Issue by braxton-butcher** [searchdiscovery/loews-dl-spec-ga4#35]

**Comment by escohen115** [comment]
Please fire the GA4 data layer event (i.e. "datalayer") in all scenarios where the Adobe data layer event (i.e. "appEventData") is firing

**Comment by brendenconcannon** [comment]
@braxton-butcher - Any feedback for this event?

**Comment by JH-SDI** [comment]
@dbokadiya @brendenconcannon 

Moved back this one to "to do" for these reasons:

User sign in event has an issue that kicks out a signed user immediately, so there is no chance for the user for actual signing out.
When the user gets kicked out, no sign out event is fired
this event needs to fire site wide

**Comment by JH-SDI** [comment]
@dbokadiya @brendenconcannon

Tested this event with the following credentials:

[alex.saveljev@nextguest.com](mailto:alex.saveljev@nextguest.com)
LoewsStaging1

Event not firing. 

Moved back to "to do"

**Comment by JH-SDI** [comment]
@dbokadiya @brendenconcannon @estum1 

Event do not fire on main site and booking engine. 


Moved to "prod Improvement"

**Comment by JH-SDI** [comment]
@dbokadiya @brendenconcannon @estum1

Event do not fire on main site and booking engine.

Moved to "prod Improvement"

**Comment by dbokadiya** [comment]
@JH-SDI 

Issue resolved in booking engine kindly review in BE.

**Comment by brendenconcannon** [comment]
@JH-SDI - devs have completed updates - can you please test?

**Comment by JH-SDI** [comment]
@brendenconcannon 

Event is firing on main site but is still not firing on the BE

**Comment by brendenconcannon** [comment]
@JH-SDI - updates have been deployed for this event. Can you please test?

**Comment by JH-SDI** [comment]
@brendenconcannon

Error persist on the BE:



![Image](https://github.com/searchdiscovery/loews-dl-spec-ga4/assets/121498633/b6a21a6d-ba0d-4b3b-8e03-2b25f0deaa64)

**Comment by brendenconcannon** [comment]
@JH-SDI - You are getting this authentication error when logging out? We have tested several credentials and have not been able to reproduce this authentication error. Are you able to try other credentials? Not sure what next steps for this one would be.

**Comment by JH-SDI** [comment]
@brendenconcannon 


Event is firing as expected:



![Image](https://github.com/searchdiscovery/loews-dl-spec-ga4/assets/121498633/18bbdc6e-ca25-49f2-8389-421f1b07487d)




Moved to complete
